title = "Flashcast"
gitSourceBranch = "main"

[home]
enabled = true

[[home.features]]
title = "straightforward"
description = "much less abstractions than the alternative resources"

[[home.features]]
title = "customizable"
description = "flashcast was made for fine-grained usage so you could implement your own systems at will"

[[home.features]]
title = "lightweight"
description = "flashcast is easy to pick up with minimal knowledge"

[docusaurus]
tagline = "simple library for bullets made for Roblox"